name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Lint & build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.0.0

      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm build